foodbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import post_comment_create_and_list_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls', namespace='profile')),
    path('posts/', include('posts.urls', namespace='posts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView, liked_posts_list_view, food_book_detail_view, PostDetailView, search_posts

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('search/', search_posts, name='search-posts'),
    path('myfoodbook/', liked_posts_list_view, name='liked_posts_view'),
    path('liked', like_unlike_post, name='like-post-view'),
    path('<pk>/', PostDetailView.as_view(), name='detail-post'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('foodbook/<slug>/', food_book_detail_view, name='liked_posts_user_profile'),
]

profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view,
    invites_received_view,
    profiles_list_view,
    invite_profiles_list_view,
    ProfileDetailView,
    ProfileListView,
    send_invitation,
    remove_from_friends,
    accept_invitation,
    reject_invitation,
    my_friends_view,
    users_friends,
)


app_name = 'profile'

urlpatterns = [
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('myfriends/', my_friends_view, name='my-friends-view'),
    path('frineds/<slug>/', users_friends, name='users-friends'),
    path('myinvites/', invites_received_view, name='my-invites-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    path('send-invite/', send_invitation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('myinvites/accept/', accept_invitation, name='accept-invite'),
    path('myinvites/reject/', reject_invitation, name='reject-invite'),
    path('<slug>/', ProfileDetailView.as_view(), name='profiles-detail-view'),
]

profiles/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from .utils import get_random_code
from django.template.defaultfilters import slugify
from django.db.models import Q
from PIL import Image
# Create your models here.


class ProfileManager(models.Manager):

    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))

        accepted = set([])
        for rel in qs:
            if rel.status == 'accepted':
                accepted.add(rel.receiver)
                accepted.add(rel.sender)
        available = [profile for profile in profiles if profile not in accepted]
        return available

    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles

    def get_friends_profiles(self, me):
        profiles = Profile.objects.filter(friends=me)
        return profiles



class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    second_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="no bio...", max_length=300)
    email = models.EmailField(max_length=200, blank=True)
    country = models.CharField(max_length=200, blank=True)
    avatar = models.ImageField(default='avatar.png', upload_to='avatars/')
    friends = models.ManyToManyField(User, blank=True, related_name='friends')
    profession = models.CharField(max_length=200, blank=True)
    slug = models.SlugField(unique=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ProfileManager()

    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%d-%m-%Y')}"

    def get_absolute_url(self):
        return reverse('profile:profiles-detail-view', kwargs={'slug': self.slug})

    def get_absolute_url_foodbook(self):
        return reverse('posts:liked_posts_user_profile', kwargs={'slug': self.slug})

    def get_friends(self):
        return self.friends.all()

    def get_friends_no(self):
        return self.friends.all().count()

    def get_posts_no(self):
        return self.posts.all().count()

    def get_all_authors_posts(self):
        return self.posts.all()

    def get_all_liked_posts(self):
        return self.like_set.filter(value='Like')

    def get_likes_given_no(self):
        likes = self.like_set.all()
        total_liked = 0
        for item in likes:
            if item.value == 'Like':
                total_liked += 1
        return total_liked

    def get_likes_received_no(self):
        posts = self.posts.all()
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()
        return total_liked

    __initial_first_name = None
    __initial_second_name = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__initial_first_name = self.first_name
        self.__initial_second_name = self.second_name

    def crop_center(self, pil_img, crop_width: int, crop_height: int) -> Image:
        """
        Функция для обрезки изображения по центру.
        """
        img_width, img_height = pil_img.size
        return pil_img.crop(((img_width - crop_width) // 2,
                             (img_height - crop_height) // 2,
                             (img_width + crop_width) // 2,
                             (img_height + crop_height) // 2))

    def save(self, *args, **kwargs):
        ex = False
        to_slug = self.slug
        if self.first_name != self.__initial_first_name and self.second_name != self.__initial_second_name or self.slug=='':
            if self.first_name and self.second_name:
                to_slug = slugify(str(self.first_name) + " " + str(self.second_name))
                ex = Profile.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + " " + str(get_random_code()))
                    ex = Profile.objects.filter(slug=to_slug).exists()
            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)
        img = Image.open(self.avatar.path)
        new_img = self.crop_center(img, 600, 600)
        new_img.save(self.avatar.path)



STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted'),
)


class RelationshipManager(models.Manager):

    def invatations_received(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status='send')
        return qs

    def invatations_sended(self, sender):
        qs = Relationship.objects.filter(sender=sender, status='send')
        return qs


class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"

profiles/forms.py
from django import forms
from .models import Profile


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'second_name', 'profession', 'bio', 'avatar')

profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Profile, Relationship
from posts.models import Post
from .forms import ProfileModelForm
from posts.forms import PostModelForm
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


@login_required
def my_profile_view(request):
    profile = Profile.objects.get(user=request.user)
    posts = Post.objects.filter(author=profile.id)
    form = ProfileModelForm(request.POST or None,  request.FILES or None, instance=profile)
    confirm = False

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True

    p_form = PostModelForm()


    if 'submit_p_form' in request.POST:
        p_form = PostModelForm(request.POST, request.FILES)
        if p_form.is_valid():
            instance = p_form.save(commit=False)
            instance.author = profile
            instance.save()
            p_form = PostModelForm()
            post_added = True


    context = {
        'profile': profile,
        'posts': posts,
        'form': form,
        'p_form': p_form,
        'confirm': confirm,
    }
    return render(request, 'profiles/myprofile.html', context)


@login_required
def invites_received_view(request):
    profile = Profile.objects.get(user=request.user)
    qs = Relationship.objects.invatations_received(profile)
    result = list(map(lambda x: x.sender, qs))
    is_empty = False
    if len(result) == 0:
        is_empty = True

    context = {
        'qs': result,
        'is_empty': is_empty,
    }
    return render(request, 'profiles/my_invites.html', context)


@login_required
def profiles_list_view(request):
    user = request.user
    qs = Profile.objects.get_all_profiles(user)

    context = {
        'qs': qs,
    }
    return render(request, 'profiles/profile_list.html', context)


@login_required
def accept_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == 'send':
            rel.status = 'accepted'
            rel.save()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profile:my-invites-view')


@login_required
def reject_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profile:my-invites-view')

#не работает
@login_required
def invite_profiles_list_view(request):
    profile = Profile.objects.get(user=request.user)
    qs = Relationship.objects.invatations_sended(profile)
    result = list(map(lambda x: x.receiver, qs))
    is_empty = False
    if len(result) == 0:
        is_empty = True

    context = {
        'qs': result,
        'is_empty': is_empty,
    }
    return render(request, 'profiles/to_invite_list.html', context)


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'profiles/detail.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        context['profile'] = profile
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['posts'] = self.get_object().get_all_authors_posts()
        if len(context['posts']) == 0:
            context['is_empty'] = True
        context['len_post'] = True if len(self.get_object().get_all_authors_posts()) > 0 else False

        return context


class ProfileListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'profiles/profile_list.html'

    def get_queryset(self):
        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        context['profile'] = profile
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['is_empty'] = False
        if len(self.get_queryset()) == 0:
            context['is_empty'] = True
        return context


@login_required
def send_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send')

        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profile:my-profile-view')


@login_required
def remove_from_friends(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.get(
            (Q(sender=sender) & Q(receiver=receiver)) | (Q(sender=receiver) & Q(receiver=sender))
        )
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profile:my-profile-view')

@login_required
def my_friends_view(request):
    user = request.user
    qs = Profile.objects.get_friends_profiles(user)
    is_empty = False
    if len(qs) == 0:
        is_empty = True
    context = {
        'qs': qs,
        'is_empty': is_empty,
    }
    return render(request, 'profiles/myfriends.html', context)


@login_required
def users_friends(request, slug):
    user = Profile.objects.get(slug=slug)
    requester = Profile.objects.get(user=request.user)
    pre_qs = []
    for item in user.friends.all():
        pre_qs.append(item)

    qs = Profile.objects.filter(user__in=pre_qs)
    is_empty = False
    if len(qs) == 0:
        is_empty = True
    rel_r = Relationship.objects.filter(sender=requester)
    rel_s = Relationship.objects.filter(receiver=requester)
    rel_receiver = []
    rel_sender = []
    for item in rel_r:
        rel_receiver.append(item.receiver.user)
    for item in rel_s:
        rel_sender.append(item.sender.user)
    context = {
        'qs': qs,
        'is_empty': is_empty,
        'profile': user,
        'rel_receiver': rel_receiver,
        'rel_sender': rel_sender
    }
    return render(request, 'profiles/users_friends.html', context)

profiles/templates/profiles/detail.html
{% extends 'base.html' %}

{% block title %}
profile detail
{% endblock title %}

{% block content %}

<div class="ui segment">
    <h2>{{object.user}}</h2>
    <div class="ui grid">
        <div class="row">
            <div class="four wide column">
                <div class="but">
                    <img class="ui medium rounded image" src="{{object.avatar.url}}">
                    <div class="row mt-5">
                        {% if object.user not in rel_receiver and object.user not in rel_sender %}
                            <form action="{% url 'profile:send-invite' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value="{{object.pk}}">
                                <button type="submit" class="ui orange button update-button">
                                    Добавить в друзья
                                </button>
                            </form>
                        {% endif %}

                        {% if object.user in rel_receiver and request.user not in object.friends.all %}
                            <button class="ui disabled button w-big update-button"><i class="user icon"></i>Заявка отправлена</button>
                        {% endif %}
                        {% if object.user in rel_sender and request.user not in object.friends.all %}
                        <div class="ui floating update-button orange icon dropdown button">
                          <span class="text">Отправил заявку</span>
                          <div class="menu">
                            <div class="item">
                              <form action="{% url 'profile:accept-invite' %}" method="POST">
                                  {% csrf_token %}
                                  <input type="hidden" name="profile_pk" value="{{object.pk}}">
                                  <button type="submit" class="ui orange button update-button">
                                    Принять заявку
                                  </button>
                                </form>
                          </div>
                            <div class="item">
                              <form action="{% url 'profile:reject-invite' %}" method="POST">
                                  {% csrf_token %}
                                  <input type="hidden" name="profile_pk" value="{{object.pk}}">
                                  <button class="ui orange button update-button" type="submit">
                                    Отклонить заявку
                                  </button>
                              </form>
                          </div>
                          </div>
                        </div>
                        {% endif %}
                        {% if request.user in object.friends.all %}
                            <form action="{% url 'profile:remove-friend' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value="{{object.pk}}">
                                <button type="submit" class="ui  orange button update-button">
                                    Удалить из друзей
                                </button>
                            </form>
                        {% endif %}
                    </div>
                    <div class="row mt-5">
                        <a href="{{object.get_absolute_url_foodbook}}"><button class="ui orange button update-button">Книга рецептов {{object.user}}</button></a>
                    </div>
                    <div class="ui vertical fluid menu">
                        <a class="item" href="{% url 'profile:users-friends' object.slug %}">
                            Друзей
                            <div class="ui label">
                                {{object.get_friends_no}}
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            <div class="twelve wide column">
                <table class="ui orange table">
                    <tbody>
                        <tr>
                            <td>Ник</td>
                            <td>{{object.user}}</td>
                        </tr>
                        <tr>
                            <td>Звание</td>
                            {% if object.first_name  %}
                            <td>{{object.profession}}</td>
                             {% else %}
                             <td>Не указано</td>
                             {% endif %}
                        </tr>
                         <tr>
                            <td>Имя</td>
                             {% if object.first_name  %}
                            <td>{{object.first_name}}</td>
                             {% else %}
                             <td>Не указано</td>
                             {% endif %}
                        </tr>
                        <tr>
                            <td>Фамилия</td>
                            {% if object.first_name  %}
                            <td>{{object.second_name}}</td>
                             {% else %}
                             <td>Не указано</td>
                             {% endif %}
                        </tr>
                    </tbody>
                </table>
                <table class="ui orange table">
                    <tbody>
                         <tr>
                            <td>Информация</td>
                            <td>{{object.bio}}</td>
                        </tr>
                    </tbody>
                </table>
                <table class="ui orange table">
                    <tbody>
                        <tr>
                            <td>Количество рецептов</td>
                            <div class="six wide column">
                            <td>{{object.get_posts_no}}</td>
                            </div>
                        </tr>
                        <tr>
                            <td>Количество полученных лайков</td>
                            <td>{{object.get_likes_received_no}}</td>
                        </tr>

                        <tr>
                            <td>Количество поставиленных лайков</td>
                            <td>{{object.get_likes_given_no}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>

<div class="ui segment">
    {% if is_empty%}
    <div class="ui message">
      <div class="header">
        У пользователя еще нет постов
      </div>
    </div>
    {% endif %}
    <div class="ui grid">
        <div class="row">
            {% for post in posts %}
            <div class="four wide column mb-38">
                <div class="ui special cards">
                  <div class="card mb-5">
                    <div class="blurring dimmable image">
                      <div class="ui dimmer">
                        <div class="content">
                          <div class="center">
                              <a href="{{post.get_absolute_url}}"><div class="ui inverted orange button">Смотреть</div></a>
<!--                              {% url 'posts:post-update' post.pk %}-->
                          </div>
                        </div>
                      </div>
                        {% if post.image %}
                            <img src={{post.image.url}}>
                        {% else %}
                            <img src="{{ MEDIA_URL }}no_image.png">
                        {% endif %}
                    </div>
                    <div class="content centerial-like-name">
                        <div class="header"><a href="{{post.get_absolute_url}}">{{post}}</a></div>
                        <div class="flex-post-short">
                            <span> {{ post.num_comments }} comments</span>
                            <div class="right floated like-recept-my-profile">
                                <form action="{% url 'posts:like-post-view' %}" method="POST" class='like-form' id='{{post.id}}'>
                                    {% csrf_token %}
                                    <input type="hidden" name="post_id" value={{post.id}}>

                                        {% if profile not in post.liked.all %}
                                            <button type="submit" class="ui orange button like-btn{{post.id}}">Like {{post.num_likes}}</button>
                                        {% else %}
                                            <button type="submit" class="ui button like-btn{{post.id}}"> Unlike {{post.num_likes}}</button>
                                        {% endif %}
                                </form>
                            </div>
                        </div>
                    </div>
                  </div>
                </div>
            </div>
            {% endfor %}
        </div>
        </div>
    </div>

{% endblock content %}

profiles/templates/profiles/my_invites.html
{% extends 'base.html' %}

{% block title %}
my invites
{% endblock title %}

{% block content %}
<div class="ui grid">
    <div class="two wide column">
    </div>
    <div class="twelve wide column">
        {% if is_empty %}
        <div class="ui message">
          <div class="header">
            У вас нет заявок в друзья.
          </div>
        </div>
        {% endif %}
        {% for obj in qs %}
        <div class="ui segment">
          <div class="ui grid">
            <div class="four wide column">
                <img class="ui small circular image" src="{{obj.avatar.url}}">
            </div>
            <div class="eight wide column">
              <a href="{{obj.get_absolute_url}}"><h3>{{obj.user}}</h3></a>
              <p>{{obj.bio}}</p>
              <form action="{% url 'profile:accept-invite' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                <button type="submit" class="ui orange button w-big mb-5">
                  Принять заявку
                </button>
              </form>
              <form action="{% url 'profile:reject-invite' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                <button type="submit" class="ui orange button w-big mb-5">
                  Отклонить заявку
                </button>
              </form>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

profiles/templates/profiles/profile_list.html
{% extends 'base.html' %}

{% block title %}
all profiles
{% endblock title %}

{% block content %}
<div class="ui grid">
    <div class="two wide column">
    </div>
    <div class="twelve wide column">
        {% if is_empty %}
        <div class="ui message">
          <div class="header">
            Других пользователей нет.
          </div>
        </div>
        {% endif %}
        {% for obj in object_list %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="four wide column">
                    <img class="ui small circular image" src="{{obj.avatar.url}}">
                </div>
                <div class="eight wide column">
                    <a href="{{obj.get_absolute_url}}"><h3>{{obj.user}}</h3></a>
                        <p>{{obj.bio}}</p>
                        {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                            <form action="{% url 'profile:send-invite' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                                <button type="submit" class="ui orange button mb-5 w-big">
                                    Добавить в друзья
                                </button>
                            </form>
                        {% endif %}
                        {% if obj.user in rel_sender and request.user not in obj.friends.all %}
                        <div class="ui floating update-button orange icon dropdown button">
                          <span class="text">Отправил заявку</span>
                          <div class="menu">
                            <div class="item">
                              <form action="{% url 'profile:accept-invite' %}" method="POST">
                                  {% csrf_token %}
                                  <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                                  <button type="submit" class="ui orange button update-button">
                                    Принять заявку
                                  </button>
                                </form>
                          </div>
                            <div class="item">
                              <form action="{% url 'profile:reject-invite' %}" method="POST">
                                  {% csrf_token %}
                                  <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                                  <button class="ui orange button update-button" type="submit">
                                    Отклонить заявку
                                  </button>
                              </form>
                          </div>
                          </div>
                        </div>
                        {% endif %}

                        {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                            <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Заявка отправлена</button>
                        {% endif %}
                        {% if request.user in obj.friends.all %}
                            <form action="{% url 'profile:remove-friend' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                                <button type="submit" class="ui orange button mb-5 w-big">
                                    Удалить из друзей
                                </button>
                            </form>
                        {% endif %}
                    </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

profiles/templates/profiles/to_invite_list.html
{% extends 'base.html' %}

{% block title %}
my invites
{% endblock title %}

{% block content %}
<div class="ui grid">
    <div class="two wide column">
    </div>
    <div class="twelve wide column">
        {% if is_empty %}
        <div class="ui message">
          <div class="header">
            У вас нет исходящих заявок в друзья.
          </div>
        </div>
        {% endif %}
        {% for obj in qs %}
        <div class="ui segment">
          <div class="ui grid">
            <div class="four wide column">
                <img class="ui small circular image" src="{{obj.avatar.url}}">
            </div>
            <div class="eight wide column">
              <a href="{{obj.get_absolute_url}}"><h3>{{obj.user}}</h3></a>
              <p>{{obj.bio}}</p>
              <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>

            </div>
          </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}