foodbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import post_comment_create_and_list_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls', namespace='profile')),
    path('posts/', include('posts.urls', namespace='posts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView, liked_posts_list_view, food_book_detail_view, PostDetailView, search_posts

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('search/', search_posts, name='search-posts'),
    path('myfoodbook/', liked_posts_list_view, name='liked_posts_view'),
    path('liked', like_unlike_post, name='like-post-view'),
    path('<pk>/', PostDetailView.as_view(), name='detail-post'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('foodbook/<slug>/', food_book_detail_view, name='liked_posts_user_profile'),
]

profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view,
    invites_received_view,
    profiles_list_view,
    invite_profiles_list_view,
    ProfileDetailView,
    ProfileListView,
    send_invitation,
    remove_from_friends,
    accept_invitation,
    reject_invitation,
    my_friends_view,
    users_friends,
)


app_name = 'profile'

urlpatterns = [
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('myfriends/', my_friends_view, name='my-friends-view'),
    path('frineds/<slug>/', users_friends, name='users-friends'),
    path('myinvites/', invites_received_view, name='my-invites-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    path('send-invite/', send_invitation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('myinvites/accept/', accept_invitation, name='accept-invite'),
    path('myinvites/reject/', reject_invitation, name='reject-invite'),
    path('<slug>/', ProfileDetailView.as_view(), name='profiles-detail-view'),
]

templates/main/home.html
{% extends 'base.html' %}

{% block title %}main page{% endblock title %}

{% block content %}
<div class="ui grid">
    <div class="two wide column">
    </div>
    <div class="twelve wide column">
        {% for obj in qs %}

        <div class="ui fluid card">
            <div class="content">
                <div class="right floated meta">
                <div class="ui grid">
                    <div class="row">
                        {% if request.user == obj.author.user %}
                            <a href="{% url 'posts:post-update' obj.pk %}"><button class="ui button bwhite-lg ">Изменить </button></a>
                            <a href="{% url 'posts:post-delete' obj.pk %}"><button class="ui button bwhite-lg ">Удалить </button></a>
                        {% endif %}
                    </div>
                </div>

                </div>
                <img class="ui avatar image" src={{obj.author.avatar.url}}>
                <a href="{{obj.author.get_absolute_url}}">{{ obj.author.user }}</a> - {{ obj.created|timesince}}
            </div>
            <div class="ui fluid image">
                {% if obj.image %}
                    <img class="ui small image" src={{obj.image.url}}>
                {% endif %}
            </div>
            <div class="content">
                <h2> <a href="{{post.author.get_absolute_url}}">{{ obj.name }}</a> </h2>
                <div class="right floated">
                    <form action="{% url 'posts:like-post-view' %}" method="POST" class='like-form' id='{{obj.id}}'>
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value={{obj.id}}>

                        {% if profile not in obj.liked.all %}
                            <button type="submit" class="ui orange button like-btn{{obj.id}}">Like {{obj.num_likes}}</button>
                        {% else %}
                            <button type="submit" class="ui button like-btn{{obj.id}}"> Unlike {{obj.num_likes}}</button>
                        {% endif %}
                    </form>
                </div>
                <i class="comment icon"></i>
                <span> {{ obj.num_comments }} comments</span>
            </div>
            <div class="extra content">
                <div class="mb-5">

                </div>
                <button class="cmt_btn ui button mb-5">show / hide comments</button>
                <div class="comment-box">
                {% if obj.comment_set.all %}
                    {% for c in obj.comment_set.all %}

                        <div class="ui segment mb-5">
                            <img class="ui avatar image" src={{c.user.avatar.url}}>
                            <span>{{ c.user }}</span>
                            <div class='mt-5'>{{ c.body }}</div>
                        </div>

                    {% endfor %}
                {% endif %}
                </div>

                <form action="" method="POST"class='ui fluid form'>
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value={{obj.id}}>
                    {{ c_form }}
                    <button type="submit" name="submit_c_form" class="ui orange  button mt-5 w-full">Send</button>
                </form>
            </div>
        </div>


        {% endfor %}
    </div>

</div>
{% endblock content %}

{% block scripts %}
    <script>
        $( document ).ready(function() {
            let display = false
            $(".cmt_btn").click(function () {
                if (display===false) {
                    $(this).next(".comment-box").show("slow");
                    display=true
                } else {
                    $(this).next(".comment-box").hide("slow");
                    display=false
                }
            });

            $('.like-form').submit(function(e){
                e.preventDefault()

                const post_id = $(this).attr('id')

                const likeText = $(`.like-btn${post_id}`).text()
                const trim = $.trim(likeText)

                const url = $(this).attr('action')

                let res;
                const likes = $(`.like-count${post_id}`).text()
                const trimCount = parseInt(likes)

                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                        'post_id':post_id,
                    },
                    success: function(response) {
                        if(trim === 'Unlike') {
                            $(`.like-btn${post_id}`).text('Like')
                            res = trimCount - 1
                        } else {
                            $(`.like-btn${post_id}`).text('Unlike')
                            res = trimCount + 1
                        }

                        $(`.like-count${post_id}`).text(res)
                    },
                    error: function(response) {
                        console.log('error', response)
                    }
                })

            })
        });
    </script>
{% endblock scripts %}

templates/main/navbar.html
{% url 'main-post-view' as path_to_home %}
{% url 'posts:search-posts' as path_to_search %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'profile:my-profile-view' as path_to_my_profile %}
{% url 'profile:my-invites-view' as path_to_my_invites %}
{% url 'profile:invite-profiles-view' as path_to_invites %}
{% url 'profile:all-profiles-view' as path_to_all_profiles %}
{% url 'profile:my-friends-view' as path_to_my_friends %}

<div class="ui inverted orange menu nav mb-7">
  <div class="ui container">
    <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item">
        <h3>foodbook</h3>
    </a>
    {% if request.user.is_authenticated %}
    <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item">
        Рецепты друзей
    </a>
    {% endif %}

    <div class="right menu">
        {% if request.user.is_authenticated %}
        <div class="item">
            <div class="ui floating dropdown icon button orange"> Друзья
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="{{path_to_my_friends}}" class="item">
                        Мои друзья
                    </a>
                    <a href="{{path_to_all_profiles}}" class="item">
                        Все пользователи
                    </a>
                    <a href="{{path_to_invites}}" class="item">
                        Исходящие заявки &nbsp; <div class="ui purple horizontal label">{{send_invites_num}}</div>
                    </a>
                    <a href="{{path_to_my_invites}}" class="item">
                        Запросы в друзья &nbsp; <div class="ui purple horizontal label">{{invites_num}}</div>
                    </a>
                </div>
             </div>
        </div>
             <div class="item">
              <form action="{{path_to_search}}" method="GET">
                <div class="ui action left icon input">
                <input class="prompt" type="text" name='search' placeholder="Поиск...">
                <i class="search icon"></i>
                <button type='submit' class="ui button">Искать</button>
                </div>
            </form>
            </div>

            <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                <img src="{{picture.url}}" class="ui avatar image">&nbsp;
                 {{ request.user }}
            </a>

            <a href="{% url 'account_logout' %}" class="ui item">
                Выйти
            </a>
        {% else %}
        <a href="{% url 'account_login' %}" class="ui item">
                Войти
            </a>
        {% endif %}
    </div>
  </div>
</div>